apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fqfumlmzo-nodejs-gitops
  description: This is GitOps manifest for fqfumlmzo-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: fqfumlmzo-nodejs
    backstage.io/kubernetes-id: fqfumlmzo-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fqfumlmzo-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fqfumlmzo-nodejs
